# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget borders active_color=0xFFDC8A78 inactive_color=0x00000000 width=2.0'
]

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top = [{ monitor."built-in" = 8}, 40]
outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-shift-h = 'focus --boundaries-action stop left'
ctrl-alt-shift-n = 'focus --boundaries-action stop down'
ctrl-alt-shift-e = 'focus --boundaries-action stop up'
ctrl-alt-shift-i = 'focus --boundaries-action stop right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-alt-shift-cmd-h = 'move left'
ctrl-alt-shift-cmd-n = 'move down'
ctrl-alt-shift-cmd-e = 'move up'
ctrl-alt-shift-cmd-i = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-alt-shift-m = 'resize smart -50'
ctrl-alt-shift-comma = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-alt-shift-j = 'workspace 1'
ctrl-alt-shift-l = 'workspace 2'
ctrl-alt-shift-u = 'workspace 3'
ctrl-alt-shift-y = 'workspace 4'
ctrl-alt-shift-semicolon = 'workspace 5'
ctrl-alt-shift-leftSquareBracket = 'workspace 6'
ctrl-alt-shift-7 = 'workspace 7'
ctrl-alt-shift-8 = 'workspace 8'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-alt-shift-cmd-j = 'move-node-to-workspace 1'
ctrl-alt-shift-cmd-l = 'move-node-to-workspace 2'
ctrl-alt-shift-cmd-u = 'move-node-to-workspace 3'
ctrl-alt-shift-cmd-y = 'move-node-to-workspace 4'
ctrl-alt-shift-cmd-semicolon = 'move-node-to-workspace 5'
ctrl-alt-shift-cmd-leftSquareBracket = 'move-node-to-workspace 6'
ctrl-alt-shift-cmd-7 = 'move-node-to-workspace 7'
ctrl-alt-shift-cmd-8 = 'move-node-to-workspace 8'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-alt-shift-cmd-s = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout

ctrl-alt-shift-cmd-h = ['join-with left', 'mode main']
ctrl-alt-shift-cmd-n = ['join-with down', 'mode main']
ctrl-alt-shift-cmd-e = ['join-with up', 'mode main']
ctrl-alt-shift-cmd-i = ['join-with right', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
comma = ['layout horizontal vertical', 'mode main']
period = ['layout tiles accordion', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#fullscreen
z = [ 'fullscreen', 'mode main' ]

## auto-move app to workspaces
# private
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 1'

# code
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 2'

# browsing
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.apple.Chrome'
run = 'move-node-to-workspace 3'

# productivity
[[on-window-detected]]
if.app-id = 'com.linear'
run = 'move-node-to-workspace 4'

# communication
[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
run = 'move-node-to-workspace 7'

