-- tailwind setup
-- local lspconfig = require("lspconfig")
-- local capabilities = require("cmp_nvim_lsp").default_capabilities()
-- local on_attach = --this is a custom function that sets several options
--   -- The initialization of TailwindCSS LSP
--   lspconfig.tailwindcss.setup({
--     on_attach = on_attach,
--     capabilities = capabilities,
--     settings = {
--       tailwindCSS = {
--         includeLanguages = {
--           fsharp = "html",
--         },
--         experimental = {
--           classRegex = {
--             "(?:_class )(?:'|\"|`)([^\"'`]*)(?:'|\"|`)", -- Giraffe.ViewEngine, looks for string preceded by '_class '
--           },
--         },
--       },
--     },
--     filetypes = {
--       "fsharp",
--       "html",
--     },

-- Add additional filetypes
-- vim.list_extend(opts.filetypes, { "fsharp" }),
-- })
