#!/bin/bash

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# INITIAL IMPORTS
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
source "$CONFIG_DIR/variables.sh"

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# VISUAL
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# main bar & defaults
sketchybar --bar height=40 \
  margin=12 \
  y_offset=0 \
  padding_left=0 \
  padding_right=0 \
  color=0x00000000

sketchybar --default \
  icon.color=$TEXT \
  label.color=$TEXT \
  label.font="Berkeley Mono Variable:Regular:14.0" \
  background.color=$BASE \
  background.height=30 \
  background.drawing=on \
  icon.padding_left=8 \
  icon.padding_right=2 \
  label.padding_left=2 \
  label.padding_right=8 \
  background.padding_left=2 \
  background.padding_right=2 \
  background.corner_radius=10 \
  background.border_width=1 \
  background.border_color=$SKY

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# ITEMS
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# left
source $ITEM_DIR/spaces.sh

# left (of notch)
source $ITEM_DIR/front_app.sh

# right (of notch)
source $ITEM_DIR/media.sh

# right
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/disk.sh
# source $ITEM_DIR/docker.sh

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# SETUP
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# load configuration
sketchybar --update
# sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
