[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "/home/viktor/.local/bin/lazygit"
description = "run lazygit"
width = "95%"
height = "95%"

[[keys.command]]
key = "prefix+alt+b"
type = "popup"
command = "/usr/bin/btop"
description = "run lazygit"
width = "95%"
height = "95%"

